{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.selectors.prometheus }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: monitoring-np-prometheus-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    {{- toYaml .Values.networkPolicy.selectors.prometheus | nindent 4}}
  policyTypes: [Egress]
  egress:
    {{- $p := .Values.networkPolicy.ports }}

    {{- if .Values.networkPolicy.prometheus.allowScrape.kubeStateMetrics }}
    - to:
        - podSelector:
            {{- toYaml .Values.networkPolicy.selectors.kubeStateMetrics | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ $p.kubeStateMetricsHttp }}
    {{- end }}

    {{- if .Values.networkPolicy.prometheus.allowScrape.nodeExporter }}
    - to:
        - podSelector:
            {{- toYaml .Values.networkPolicy.selectors.nodeExporter | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ $p.nodeExporterMetrics }}
    {{- end }}

    {{- if .Values.networkPolicy.prometheus.allowScrape.selfFederate }}
    - to:
        - podSelector:
            {{- toYaml .Values.networkPolicy.selectors.prometheus | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ $p.prometheusHttp }}
    {{- end }}

    {{- if .Values.networkPolicy.prometheus.allowScrape.alertmanager }}
    - to:
        - podSelector:
            {{- toYaml .Values.networkPolicy.selectors.alertmanager | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ $p.alertmanagerHttp }}
    {{- end }}
{{- end }}
